### ISSUE TITLE
Changes to parseschema2.py

### ISSUE THREAD

**Issue by ahwitz** [DDMAL/libmei#90]
refs #88

A few small changes should be made to parseschema2:

1) Print out diagnostic information if any of the languages put in using the -l flag are not supported.

1.1) @AFFogarty also wants the -l flag to no longer be case sensitive so `-l Python` and `-l python` and `-l PyThOn` would work identically.

1.2) Change the `--help` flag to show that you can do multiple languages at the same time.

2) In the case where neither `-sl` OR `[compiled]` are present in the invocation (such as `python parseschema2.py -l cpp`), the warning message defaults to a message about `-sl` if the user has input other parameters. This is an edge case for misuse, but I think the default should be a message about the `[compiled]` parameter if it's missing. @ahankinson can correct me if he thinks otherwise.

**Comment by ahankinson** [comment]
1) OK

1.1) pretty easy: arg = arg.lower()

1.2) pretty easy too

2. Try it with exclusive groups, a la our process.py script for Diva.

**Comment by ifkarp** [comment]
1.1 has been fixed in commit 528c1a959e04ae1466bf3ab0db04226eb0e06c88 

For 1.2 I'm working on allowing the `-l` flag to take in a variable number of languages without consuming other flags or `compiled` (When this is done then fixing 1 and 1.2 will be easily changed)

2. Right now when I use neither `-sl` or `compiled` I get the error message:

`parseschema2.py: error: one of the arguments compiled -sl/--showlang is required` which does show `compiled` is needed, but it's true that it's not very clear. I'll try and clean it up a bit.

**Comment by ifkarp** [comment]
Allowed multiple languages in this commit: cb09daa78f46bef450e6efa329c8d28d0ac4331c

Added an error message for using improper languages and changed the `--help` flag output: fe21bae56a494a39e8f69bf6737dff3912efcafb

**Comment by ifkarp** [comment]
Made the error message clearer for 2) in this commit: 4f5cff652f5800dbab03c7ceac37d749eaf48b15
